---

- name: Create join directory on workers
  file:
    path: /join
    state: directory

- name: Copy join to node
  copy:
    src: ./join/kubejoin.sh
    dest: /opt/kubejoin.sh
    mode: '0700'
  tags: [copy-join]

- name: Run command on remote
  shell: /opt/kubejoin.sh

