- name: Instalar k8s e pacotes docker
  become: yes
  hosts: tag_name_k8s
  roles:
    - docker
    - k8s-all

- name: Setup master code
  become: yes
  hosts: tag_type_master
  roles:
    - k8s-master

- name: Setup worker code
  become: yes
  hosts: tag_type_worker
  roles:
    - k8s-worker