- name: Destroy cluster before starting again
  command: kubeadm reset -f

- name: Initialize k8s cluster
  command: kubeadm init
  register: kubeadm_init_output

- name: Create file with output
  copy:
    content: "{{ kubeadm_init_output.stdout }}"
    dest: /root/kubeadminit

- name: Prepare kubejoin script
  shell: tail -2 /root/kubeadminit > /root/kubejoin.sh

- name: Get kubejoin
  fetch:
    dest: ./join
    src: /root/kubejoin.sh

- name: Iniciar kubelet
  systemd:
    name: kubelet
    state: started

- name: Download Calico YAML
  uri:
    url: "https://github.com/projectcalico/calico/raw/master/manifests/calico.yaml"
    dest: "/root/calico.yaml"

- name: Apply Calico YAML
  command: kubectl apply -f /root/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
#- name: Organize files
#  command:
#    cp join/{{ inventory_hostname }}/root/kubejoin.sh ./join
##    rm -rf join/{{ inventory_hostname }}
#  delegate_to: localhost
#  become: no

#- name: Install pod network
#  command: kubectl apply -f https://docs.projectcalico.org/archive/v3.20/manifests/calico.yaml
#  environment:
#    KUBECONFIG: /etc/kubernetes/admin.conf
