---
- name: Install prereq docker
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop: "{{ docker_prereqs_packages }}"

- name: Add docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
  apt:
    name: "{{ item }}"
  loop: "{{ docker_packages }}"

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Installing package containerd.io
  apt:
    name: containerd.io
    state: present

- name: Removing conf file containerd
  file:
    path: /etc/containerd/config.toml
    state: absent

- name: Restarting containerd service
  systemd:
    name: containerd
    state: restarted